package cmd

import (
	"github.com/goken/generators"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"log"
)

var interfaceName = ""

var grpcTransportCmd = &cobra.Command{
	Use: "grpcTransport",
	Aliases: []string{"gt"},
	Short: "Generate grpc transport from *.proto file",
	Run: func(cmd *cobra.Command, args []string) {
		if len(args) == 0 {
			log.Fatal("You need to provide path to your generated by protobuf *.pb.go file with filename included. Example ./pb/service.pb.go")
		}
		if err := generators.GrpcServer(args[0], interfaceName); err != nil {
			log.Fatal(err)
		}
	},
}

func init() {
	grpcTransportCmd.Flags().StringVarP(&packageName, "package", "p", packageName, "Provide package name for service")
	viper.BindPFlag("ken_package", serviceCmd.Flags().Lookup("package"))
	grpcTransportCmd.Flags().StringVarP(&interfaceName, "interface name", "i", interfaceName, "Provide name of grpc service (required)")
	newCmd.AddCommand(grpcTransportCmd)
}
