package logic

// >> Things represented below is auto-generated by KEN Generator <<

// Add your methods below in interface
type HelloService interface {
	Method1() error
	methods2(err error) error
	Methods3(r interface{}) interface{}
}

// Struct which should implements this interface
type helloService struct {
}

func (h helloService) Method1() error {
	panic("implement me")
}

func (h helloService) methods2(err error) error {
	panic("implement me")
}

func (h helloService) Methods3(r interface{}) interface{} {
	panic("implement me")
}

// New function for initialize service
func NewHelloService() HelloService {
	return &helloService{}

}
